# Generated by Django 4.0.4 on 2022-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_owner_customer_owner_susbscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='users.customer'),
        ),
    ]
