# Generated by Django 4.0.4 on 2022-06-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='susbscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
